1
SELECT DEPARTMENT_NAME,COUNT(EMPLOYEE_ID) AS NO_OF_EMPLOYEES 
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON
E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING COUNT(EMPLOYEE_ID)>=20;



2
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES E
WHERE SALARY>(SELECT AVG(SALARY)FROM EMPLOYEES X
WHERE E.DEPARTMENT_ID=X.DEPARTMENT_ID
GROUP BY E.EMPLOYEE_ID) 


3
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,(FIRST_NAME||''||LAST_NAME)
FULL_NAME,SALARY,(SALARY*0.1)NEW_SALARY,(SALARY-(SALARY*0.1))
DIFFERENCE FROM EMPLOYEES;



4
SELECT A.EMPLOYEE_ID,A.FIRST_NAME,A.LAST_NAME,B.FIRST_NAME AS MANAGER_NAME
FROM EMPLOYEES 
A LEFT OUTER JOIN EMPLOYEES B ON A.MANAGER_ID=B.MANAGER_ID
ORDER BY EMPLOYEE_ID;


5
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY
FROM(SELECT*FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM<=3
ORDER BY SALARY;